// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.0--rc1
// source: grpcsupport/grpc.proto

package grpcsupport

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SaveServiceClient is the client API for SaveService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SaveServiceClient interface {
	Save(ctx context.Context, in *Profile, opts ...grpc.CallOption) (*Response, error)
}

type saveServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSaveServiceClient(cc grpc.ClientConnInterface) SaveServiceClient {
	return &saveServiceClient{cc}
}

func (c *saveServiceClient) Save(ctx context.Context, in *Profile, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/javCrawler.SaveService/Save", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SaveServiceServer is the server API for SaveService service.
// All implementations must embed UnimplementedSaveServiceServer
// for forward compatibility
type SaveServiceServer interface {
	Save(context.Context, *Profile) (*Response, error)
	mustEmbedUnimplementedSaveServiceServer()
}

// UnimplementedSaveServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSaveServiceServer struct {
}

func (UnimplementedSaveServiceServer) Save(context.Context, *Profile) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Save not implemented")
}
func (UnimplementedSaveServiceServer) mustEmbedUnimplementedSaveServiceServer() {}

// UnsafeSaveServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SaveServiceServer will
// result in compilation errors.
type UnsafeSaveServiceServer interface {
	mustEmbedUnimplementedSaveServiceServer()
}

func RegisterSaveServiceServer(s grpc.ServiceRegistrar, srv SaveServiceServer) {
	s.RegisterService(&SaveService_ServiceDesc, srv)
}

func _SaveService_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Profile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaveServiceServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/javCrawler.SaveService/Save",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaveServiceServer).Save(ctx, req.(*Profile))
	}
	return interceptor(ctx, in, info, handler)
}

// SaveService_ServiceDesc is the grpc.ServiceDesc for SaveService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SaveService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "javCrawler.SaveService",
	HandlerType: (*SaveServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Save",
			Handler:    _SaveService_Save_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpcsupport/grpc.proto",
}
